---
name: Checks

on: [push]

jobs:
#id
  test-lint:
  #User-friendly name
    name: Test and Lint
    #os
    runs-on: ubuntu-20.04
    #things that run for the job
    steps:
      - name: Login to Docker Hub
      #allows to use premade actions in github repository,this is login action
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        #checks out code in github action job
      - name: Checkout
        uses: actions/checkout@v2
        #runs test
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"        
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"